export default function Terms() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-200 px-6 py-12">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-white mb-2">Terms and Conditions</h1>
        <p className="text-gray-400 mb-8">Last updated: June 16, 2026</p>

        <div className="space-y-6 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-2">1. Acceptance of Terms</h2>
            <p>
              By calling a phone number powered by LeadRecall AI and engaging in text message
              communication, you agree to these Terms and Conditions. If you do not agree, you may
              opt out at any time by replying STOP to any message.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">2. Service Description</h2>
            <p>
              LeadRecall AI provides an automated text-back service for local businesses. When you
              call a business and the call is not answered, our service sends you a text message to
              acknowledge your call and offer assistance via text. An AI assistant may facilitate
              the initial conversation to understand your needs and connect you with the business.
            </p>
          </section>

          <section id="sms-consent">
            <h2 className="text-xl font-semibold text-white mb-2">3. SMS Consent &amp; Opt-In Disclosure</h2>
            <p className="mb-3">
              <strong className="text-white">By calling a LeadRecall AI-powered business phone number, you expressly consent to receive SMS text messages</strong> from that business via the LeadRecall AI platform. This consent is obtained as follows:
            </p>
            <ul className="list-disc list-inside space-y-2 mb-4">
              <li>
                When you call a participating business number, you will hear an automated voice greeting that clearly states: <em>"We will send you a text message to help with your inquiry."</em>
              </li>
              <li>
                By remaining on the line and not disconnecting during this disclosure, you provide your express consent to receive SMS messages from the business you called.
              </li>
              <li>
                If you do not wish to receive text messages, simply hang up before the greeting completes. No messages will be sent.
              </li>
            </ul>
            <p className="mb-3">
              <strong className="text-white">Message Frequency:</strong> Message frequency varies. You may receive 1-10 messages per conversation depending on your inquiry. No recurring or promotional messages are sent.
            </p>
            <p className="mb-3">
              <strong className="text-white">Message and Data Rates:</strong> Message and data rates may apply. Check with your mobile carrier for details.
            </p>
            <p className="mb-3">
              <strong className="text-white">Carriers Supported:</strong> Compatible with all major US carriers including AT&amp;T, T-Mobile, Verizon, and others.
            </p>
            <p>
              <strong className="text-white">Consent is not a condition of purchase.</strong> You are not required to consent to SMS messaging to receive services from the business you called.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">4. Opt-Out &amp; Help</h2>
            <p className="mb-3">
              You may opt out of receiving messages at any time by replying <strong className="text-white">STOP</strong>{" "}
              to any message. You will receive a single confirmation message and no
              further messages will be sent unless you initiate contact again by calling the business number.
            </p>
            <p className="mb-3">
              Reply <strong className="text-white">HELP</strong> to any message for assistance, or contact us at{" "}
              <a href="mailto:support@leadrecallai.com" className="text-blue-400 hover:underline">
                support@leadrecallai.com
              </a>.
            </p>
            <p>
              <strong className="text-white">Opt-out keywords:</strong> STOP, CANCEL, UNSUBSCRIBE, QUIT, END<br />
              <strong className="text-white">Help keywords:</strong> HELP, INFO
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">5. AI-Powered Communication</h2>
            <p>
              Some or all of the text messages you receive may be generated by artificial
              intelligence. While we strive for accuracy, AI-generated responses may occasionally
              contain errors. The business you called is responsible for confirming any
              appointments, quotes, or commitments made during the conversation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">6. Limitation of Liability</h2>
            <p>
              LeadRecall AI is provided "as is" without warranties of any kind. We are not liable
              for any damages arising from the use of our service, including but not limited to
              missed appointments, miscommunications, or service interruptions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">7. Modifications</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the service
              after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">8. Contact</h2>
            <p>
              For questions about these Terms or our SMS practices, contact us at:{" "}
              <a href="mailto:support@leadrecallai.com" className="text-blue-400 hover:underline">
                support@leadrecallai.com
              </a>
            </p>
            <p className="mt-2">
              LeadRecall AI<br />
              Houston, TX
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
