export default function Terms() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-200 px-6 py-12">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-white mb-2">Terms and Conditions</h1>
        <p className="text-gray-400 mb-8">Last updated: June 15, 2026</p>

        <div className="space-y-6 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-2">1. Acceptance of Terms</h2>
            <p>
              By calling a phone number powered by LeadRecall AI and engaging in text message
              communication, you agree to these Terms and Conditions. If you do not agree, you may
              opt out at any time by replying STOP to any message.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">2. Service Description</h2>
            <p>
              LeadRecall AI provides an automated text-back service for local businesses. When you
              call a business and the call is not answered, our service sends you a text message to
              acknowledge your call and offer assistance via text. An AI assistant may facilitate
              the initial conversation to understand your needs and connect you with the business.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">3. Consent to Receive Messages</h2>
            <p>
              By placing a call to a LeadRecall AI-powered phone number, you consent to receive
              text messages in response to your call. Message frequency varies based on your
              interaction. Message and data rates may apply depending on your mobile carrier plan.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">4. Opting Out</h2>
            <p>
              You may opt out of receiving messages at any time by replying <strong>STOP</strong>{" "}
              to any message. After opting out, you will receive a confirmation message and no
              further messages will be sent unless you initiate contact again. Reply{" "}
              <strong>HELP</strong> for assistance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">5. AI-Powered Communication</h2>
            <p>
              Some or all of the text messages you receive may be generated by artificial
              intelligence. While we strive for accuracy, AI-generated responses may occasionally
              contain errors. The business you called is responsible for confirming any
              appointments, quotes, or commitments made during the conversation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">6. Limitation of Liability</h2>
            <p>
              LeadRecall AI is provided "as is" without warranties of any kind. We are not liable
              for any damages arising from the use of our service, including but not limited to
              missed appointments, miscommunications, or service interruptions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">7. Modifications</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the service
              after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">8. Contact</h2>
            <p>
              For questions about these Terms, contact us at:{" "}
              <a href="mailto:support@leadrecallai.com" className="text-blue-400 hover:underline">
                support@leadrecallai.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
